### ISSUE TITLE
error api :(

### ISSUE THREAD

**Issue by hoangvn9x** [poketo/manga-rock-image-decoder#4]
https://api.mangarockhd.com/query/
web400/pages?oid=mrs-chapter-100083895&country=United%20States

Today, when I use the app, I get this error : "{"code":109,"data":"Unknown Query Version"}"

**Comment by rosszurowski** [comment]
Which app are you referring to? Are you using the Poketo Reader ([poketo.app](https://poketo.app)) or the Poketo CLI ([Github](https://github.com/poketo/cli))? This repository is for the image decoder.

It seems like MangaRock updated their API to use a new prefix. Instead of `web400` try `web401`, like so:

```
https://api.mangarockhd.com/query/web401/pages?oid=mrs-chapter-100083895&country=United%20States
```

I've since updated both the CLI and reader to resolve this issue. But if you're still having trouble I can try and resolve it.

**Comment by hoangvn9x** [comment]
how to you know it was moved to web 401?
thank you.

**Comment by rosszurowski** [comment]
It was just a guess based on the URL. Unfortunately, MangaRock's API isn't public, so changes like this aren't documented anywhere :(

Anyways, glad things are working again — thanks for reporting.
