### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by rahasiadong** [poketo/manga-rock-image-decoder#5]
how do i convert it to php version ?

**Comment by rosszurowski** [comment]
How do you rewrite this library in PHP? I'm not sure, it's been a while since I've done much PHP work. But these links might help you:

* The [`lib/decode.js`](https://github.com/poketo/manga-rock-image-decoder/blob/414d9cb1ce2ff8fc294aa1f738a6928c74935eca/lib/decode.js) file in this repo contains all the logic to decode the .mri images.
* [This reddit answer](https://www.reddit.com/r/codes/comments/7mdx70/need_help_decrypting_this_string/) helped me figure out how to decode them.
* The [Tachiyomi codebase](https://github.com/inorichi/tachiyomi) has an implementation of this same script in Java that you could reference.

**Comment by rosszurowski** [comment]
I’m gonna close this issue, but drop me some questions if you get stuck.
